# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Urbit
tagline:          'Personal Cloud Computing'
description:      'a personal cloud computer.'
url:              http://urbit.org

post_groups:
  - key: axis

author:
  name:           'Tlon'
  url:            https://tlon.io

paginate:         5

# Custom vars
version:          544 Kelvin

github:
  repo:           https://github.com/urbit/urbit

authors:
  cgy:
    display_name: ~tasfyn-partyv [Curtis Yarvin]
    email: curtis@tlon.io
    github: cgyarvin

  jcb:
    display_name: ~tomsyt-balsen [John Burnham]
    email: john@tlon.io
    github: johncburnham

  atax1a:
    display_name: '~hatteb-mitlyd "atax1a"'
    email: atax1a@fantastic.braintec.ch
    github: atax1a
